services:
  - type: web
    name: openai-proxy
    runtime: image
    image:
    envVars:
      - key: PORT
        value: 4000
    numInstances: 1
    healthCheckPath: /health/liveliness
    autoDeploy: true
