services:
  - type: web
    name: openai-proxy
    runtime: image
    image:
      url: ghcr.io/berriai/litellm:main-stable
    envVars:
      - key: PORT
        value: 4000
    # numInstances: 1 (Remove: Free tier is locked to 1)
    # healthCheckPath: /health/liveliness (Remove: Not supported on Free tier)
    autoDeploy: true
